name: widject_container
description: Dependency Injection Container to structure your application in loosely coupled components. Inspired by VContainer.
version: 0.1.15
homepage: https://github.com/zlatancld/WidjectContainer
repository: https://github.com/zlatancld/WidjectContainer

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
